# This Dockerfile is used with the CI/CD where the build is done on the github runner so no additional builder is required
# Serve the static files with Nginx
FROM nginx:alpine

# Copy custom nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the pre-built static bundle directly
COPY --chown=nginx:nginx dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
