---
- name: Install Kubernetes Add-ons (Ingress & Cert-Manager)
  hosts: master
  become: true
  vars_files:
    - vars.yml

  vars_prompt:
    - name: cert_manager_email
      prompt: "Enter email for Let's Encrypt certificates (ignored if defined in vars.yml)"
      private: false
      when: cert_manager_email is not defined

  tasks:
    - name: Create manifests directory
      file:
        path: /tmp/k8s-manifests
        state: directory

    - name: Apply Nginx Ingress Controller
      kubernetes.core.k8s:
        src: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.15.1/deploy/static/provider/cloud/deploy.yaml
        state: present

    - name: Apply Cert-Manager
      kubernetes.core.k8s:
        src: https://github.com/cert-manager/cert-manager/releases/download/v1.20.2/cert-manager.yaml
        state: present

    - name: Wait for Cert-Manager to be ready
      pause:
        seconds: 30

    - name: Generate ClusterIssuer from template
      template:
        src: templates/cluster-issuer.yaml.j2
        dest: /tmp/k8s-manifests/cluster-issuer.yaml

    - name: Apply ClusterIssuer
      kubernetes.core.k8s:
        state: present
        src: /tmp/k8s-manifests/cluster-issuer.yaml
