apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

commonLabels:
  env: dev

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: NODE_ENV
        value: development
  target:
    kind: Deployment
    name: backend
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: VITE_APP_VERSION
        value: swift-wolf-baffa9e
  target:
    kind: Deployment
    name: frontend
images:
- name: villejuhan1/quiz-backend
  newName: villejuhan1/quiz-backend
  newTag: swift-wolf-baffa9e
- name: villejuhan1/quiz-frontend
  newName: villejuhan1/quiz-frontend
  newTag: swift-wolf-baffa9e
