apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Patches the postgres/backend/frontend deployment for development environment in dev workspace and configures ingress for it
resources:
- ../../base

namespace: dev


patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend
    spec:
      template:
        spec:
          containers:
            - name: backend
              env:
                - name: NODE_ENV
                  value: dev
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
    spec:
      template:
        spec:
          containers:
            - name: frontend
              env:
                - name: VITE_APP_VERSION
                  value: mighty-owl-a50bb72
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 10m
                  memory: 64Mi
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres
    spec:
      template:
        spec:
          containers:
            - name: postgres
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: dev.quizgame.hiekkalaatikko.tech
    - op: replace
      path: /spec/rules/0/host
      value: dev.quizgame.hiekkalaatikko.tech
  target:
    kind: Ingress
    name: quiz-ingress
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: dev.hiekkalaatikko.tech
    - op: replace
      path: /spec/rules/0/host
      value: dev.hiekkalaatikko.tech
  target:
    kind: Ingress
    name: frontpage-ingress
- patch: |-
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: dev-db-secret
    - op: replace
      path: /spec/data/1/remoteRef/key
      value: dev-db-secret
    - op: replace
      path: /spec/data/2/remoteRef/key
      value: dev-db-secret
    - op: replace
      path: /spec/data/3/remoteRef/key
      value: dev-db-secret
  target:
    kind: ExternalSecret
    name: db-secret-sync
- patch: |-
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: dev-app-secret
    - op: replace
      path: /spec/data/1/remoteRef/key
      value: dev-app-secret
    - op: replace
      path: /spec/data/2/remoteRef/key
      value: dev-app-secret
  target:
    kind: ExternalSecret
    name: app-secret-sync

images:
- name: villejuhan1/frontpage
  newName: villejuhan1/frontpage
  newTag: front-playful-sandbox-15b3fe7
- digest: sha256:ff30f0b97dc267978ad781e7e9cb0959c8ea6936c0753e243b3f8dcf88836c34
  name: villejuhan1/quiz-backend
  newName: villejuhan1/quiz-backend
- digest: sha256:c3ba5b4b20a490290396e2db21cd42c722f4112b37ba9987628b19339d0855d3
  name: villejuhan1/quiz-frontend
  newName: villejuhan1/quiz-frontend
labels:
- includeSelectors: true
  pairs:
    env: dev
