apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret-sync
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: oci-vault-store
    kind: SecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: "placeholder-app-secret" # The secret name (or OCID) in OCI Vault
        property: JWT_SECRET # Key inside the OCI JSON secret
    - secretKey: PASSWORD_SECRET
      remoteRef:
        key: "placeholder-app-secret"
        property: PASSWORD_SECRET
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: "placeholder-app-secret"
        property: STRIPE_SECRET_KEY
