apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret-sync
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: oci-vault-store
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: "placeholder-db-secret" # The secret name (or OCID) in OCI Vault
        property: DATABASE_URL
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: "placeholder-db-secret"
        property: POSTGRES_PASSWORD
