# backend.conf
# OCI provides a native HTTP backend for Terraform state using Pre-Authenticated Requests (PAR)
# on an Object Storage bucket.
#
# To initialize Terraform, use:
# terraform init -backend-config=backend.conf

address       = "https://objectstorage.<region>.oraclecloud.com/p/<pre-authenticated-request-url>/n/<namespace>/b/<bucket-name>/o/terraform.tfstate"
update_method = "PUT"
