// Generated by Gemini 3.1 Pro (High) for Antigravity IDE
import { Component } from 'react';
import type { ErrorInfo, ReactNode } from 'react';

interface Props {
  children?: ReactNode;
  fallback?: ReactNode;
}

interface State {
  hasError: boolean;
  error?: Error;
}

/**
 * ErrorBoundary catches unhandled JavaScript errors anywhere in its child
 * component tree, logs those errors to the console, and displays a fallback UI
 * to prevent the entire application from crashing.
 *
 * It supports a custom fallback UI passed as a prop, otherwise rendering a default
 * full-page error view with the error message and a return-to-menu button.
 */
export class ErrorBoundary extends Component<Props, State> {
  public state: State = {
    hasError: false,
  };

  public static getDerivedStateFromError(error: Error): State {
    // Update state so the next render will show the fallback UI
    return { hasError: true, error };
  }

  public componentDidCatch(error: Error, errorInfo: ErrorInfo) {
    // Log the error to an error reporting service or console
    console.error('Uncaught error logged from ErrorBoundary:');
    console.error(error, errorInfo);
  }

  public render() {
    if (this.state.hasError) {
      if (this.props.fallback) {
        return this.props.fallback;
      }

      // Default fallback UI
      return (
        <div
          className="container flex-center"
          style={{ minHeight: '100vh', padding: '2rem' }}
        >
          <div
            className="glass-panel"
            style={{ padding: '3rem', textAlign: 'center', maxWidth: '600px' }}
          >
            <h1 style={{ color: 'var(--color-danger)', marginBottom: '1rem' }}>
              Oops!
            </h1>
            <h2 style={{ fontSize: '1.25rem' }}>Something went wrong.</h2>
            <p
              style={{
                marginTop: '1rem',
                padding: '1rem',
                background: 'rgba(0,0,0,0.2)',
                borderRadius: 'var(--radius-sm)',
              }}
            >
              {this.state.error?.message || 'Unknown Application Error'}
            </p>
            <button
              className="btn btn-primary"
              style={{ marginTop: '2rem' }}
              onClick={() => (window.location.href = '/')}
            >
              Return to Menu
            </button>
          </div>
        </div>
      );
    }

    return this.props.children;
  }
}
