#!/bin/bash
set -e

# Generated by Gemini 3.1 Pro and Antigravity IDE
echo "=========================================="
echo "OCI Bastion Tunnel Automation"
echo "=========================================="

# 1. Ask for local private key (for the bastion connection)
read -p "Enter path to your local private SSH key [~/.ssh/id_rsa]: " PRIVATE_KEY
PRIVATE_KEY=${PRIVATE_KEY:-~/.ssh/id_rsa}
PUBLIC_KEY="${PRIVATE_KEY}.pub"

if [ ! -f "$PUBLIC_KEY" ]; then
    echo "Error: Public key $PUBLIC_KEY not found!"
    exit 1
fi

echo "[*] Using public key $PUBLIC_KEY"

# 2. Extract IPs and Bastion ID
echo "[*] Fetching Bastion ID from Terraform..."
cd ../terraform/countriesApp
BASTION_ID=$(terraform output -raw bastion_id)
cd ../../ansible

echo "[*] Bastion ID: $BASTION_ID"

MASTER_IP=$(grep -A1 '\[k3s_master\]' inventory.ini | tail -n1 | awk '{print $1}')
WORKER_IP=$(grep -A1 '\[k3s_worker\]' inventory.ini | tail -n1 | awk '{print $1}')

echo "[*] Master Node IP: $MASTER_IP"
echo "[*] Worker Node IP: $WORKER_IP"

# 3. Create Sessions Function
create_tunnel() {
    TARGET_IP=$1
    TARGET_PORT=$2
    LOCAL_PORT=$3
    NAME=$4

    echo "[*] Creating Bastion session for $NAME ($TARGET_IP:$TARGET_PORT)... this takes ~30 seconds."
    
    # Create session and wait for it to be active
    SESSION_JSON=$(oci bastion session create-port-forwarding \
        --bastion-id $BASTION_ID \
        --display-name "Ansible-$NAME" \
        --ssh-public-key-file $PUBLIC_KEY \
        --target-private-ip $TARGET_IP \
        --target-port $TARGET_PORT \
        --session-ttl 10800 \
        --wait-for-state ACTIVE)
        
    # Extract the session ID using grep and cut to avoid needing jq
    SESSION_ID=$(echo "$SESSION_JSON" | grep -o '"id": "[^"]*' | head -n1 | cut -d'"' -f4)
    
    # Get the connection command
    SSH_CMD=$(oci bastion session get --session-id $SESSION_ID --query 'data."ssh-metadata".command' --raw-output)
    
    # Substitute placeholders with actual values
    SSH_CMD=${SSH_CMD/"<privateKey>"/$PRIVATE_KEY}
    SSH_CMD=${SSH_CMD/"<localPort>"/$LOCAL_PORT}
    
    echo "[*] Opening local tunnel on port $LOCAL_PORT..."
    # Run SSH in the background. We add StrictHostKeyChecking=no to avoid prompts
    SSH_CMD=${SSH_CMD/"ssh -i"/"ssh -o StrictHostKeyChecking=no -i"}
    eval "$SSH_CMD" &
    
    # Save the PID so we can easily kill it later
    echo $! >> bastion_pids.txt
}

# Clean up previous PIDs
rm -f bastion_pids.txt

# Open the three required tunnels
create_tunnel $MASTER_IP 22 2222 "Master-SSH"
create_tunnel $WORKER_IP 22 2223 "Worker-SSH"
create_tunnel $MASTER_IP 6443 6443 "Master-KubeAPI"

echo "[*] Tunnels are active in the background!"

# 4. Generate local inventory
echo "[*] Generating inventory.local.ini for Ansible..."
cat <<EOF > inventory.local.ini
[k3s_master]
127.0.0.1 ansible_port=2222 ansible_user=ubuntu ansible_ssh_private_key_file=ansible_key.pem

[k3s_worker]
127.0.0.1 ansible_port=2223 ansible_user=ubuntu ansible_ssh_private_key_file=ansible_key.pem

[k3s_cluster:children]
k3s_master
k3s_worker
EOF

echo "=========================================="
echo "[*] Done! You can now run Ansible:"
echo "    cd ../ansible"
echo "    ansible-playbook -i inventory.local.ini playbook.yml"
echo ""
echo "[*] To close the tunnels later, run: kill \$(cat bastion_pids.txt)"
echo "=========================================="
