#!/usr/bin/env python3
import os
import subprocess
import json
import time

# Generated by Gemini 3.1 Pro
print("==========================================")
print("OCI Bastion Tunnel Automation (Python)")
print("==========================================")

# 1. Ask for local private key
env_key = None
if os.path.isfile(".env"):
    with open(".env", "r") as f:
        for line in f:
            if line.startswith("BASTION_SSH_KEY="):
                env_key = line.split("=", 1)[1].strip()

if env_key:
    private_key_path = os.path.expanduser(env_key)
    print(f"[*] Found SSH key in .env file: {private_key_path}")
else:
    private_key_path = input("Enter path to your local private SSH key, ie. [~/.ssh/id_rsa]: ").strip()
    if not private_key_path:
        private_key_path = os.path.expanduser("~/.ssh/id_rsa")
    else:
        private_key_path = os.path.expanduser(private_key_path)

public_key_path = private_key_path + ".pub"

if not os.path.isfile(public_key_path):
    print(f"Error: Public key {public_key_path} not found!")
    exit(1)

print(f"[*] Using public key: {public_key_path}")

# 2. Extract Bastion ID from Terraform
print("[*] Fetching Bastion ID from Terraform...")
try:
    bastion_id = subprocess.check_output(
        ["terraform", "output", "-raw", "bastion_id"],
        cwd="../terraform/countriesApp",
        text=True
    ).strip()
    print(f"[*] Bastion ID: {bastion_id}")
except Exception as e:
    print("Error fetching Bastion ID from Terraform. Is it applied?")
    exit(1)

# 3. Read Inventory
print("[*] Reading Ansible inventory...")
inventory_path = "../ansible/inventory.ini"
if not os.path.isfile(inventory_path):
    print(f"Error: Inventory file {inventory_path} not found!")
    exit(1)

master_ip = None
worker_ip = None

with open(inventory_path, 'r') as f:
    lines = f.readlines()
    for i, line in enumerate(lines):
        if '[k3s_master]' in line.strip() and i + 1 < len(lines):
            master_ip = lines[i+1].split()[0]
        if '[k3s_worker]' in line.strip() and i + 1 < len(lines):
            worker_ip = lines[i+1].split()[0]

if not master_ip or not worker_ip:
    print("Error: Could not parse Master or Worker IP from inventory.ini")
    exit(1)

print(f"[*] Master Node IP: {master_ip}")
print(f"[*] Worker Node IP: {worker_ip}")

pids = []

oci_cmd = "oci"
if not os.path.exists(oci_cmd) and os.path.exists("../venv/oci-automation/bin/oci"):
    oci_cmd = "../venv/oci-automation/bin/oci"

def create_tunnel(target_ip, target_port, local_port, name):
    print(f"\n[*] Creating Bastion session for {name} ({target_ip}:{target_port})... this takes ~30 seconds.")
    
    cmd = [
        oci_cmd, "bastion", "session", "create-port-forwarding",
        "--bastion-id", bastion_id,
        "--display-name", f"Ansible-{name}",
        "--ssh-public-key-file", public_key_path,
        "--target-private-ip", target_ip,
        "--target-port", str(target_port),
        "--session-ttl", "10800"
    ]
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        # Parse JSON to safely get the ID
        session_data = json.loads(result.stdout)
        session_id = session_data['data']['id']
    except subprocess.CalledProcessError as e:
        print(f"\n[!] Error creating Bastion session for {name}!")
        print(f"Exit code: {e.returncode}")
        print("---- OCI CLI STDOUT ----")
        print(e.stdout)
        print("---- OCI CLI STDERR ----")
        print(e.stderr)
        print("------------------------------")
        return False
    except json.JSONDecodeError:
        print("\n[!] Error parsing OCI JSON response.")
        print(result.stdout)
        return False
    
    # Get SSH command
    print("[*] Waiting for session to become ACTIVE...")
    try:
        cmd_get = [
            oci_cmd, "bastion", "session", "get",
            "--session-id", session_id
        ]
        
        while True:
            res_get = subprocess.run(cmd_get, capture_output=True, text=True, check=True)
            data_get = json.loads(res_get.stdout)
            state = data_get['data']['lifecycle-state']
            
            if state == "ACTIVE":
                ssh_cmd = data_get['data']['ssh-metadata']['command']
                print("[*] Session is ACTIVE. Waiting 15 seconds for Bastion key propagation...")
                time.sleep(15)
                break
            elif state in ["FAILED", "DELETED"]:
                print(f"\n[!] Session entered failed state: {state}")
                return False
                
            time.sleep(3)
            
    except subprocess.CalledProcessError as e:
        print(f"\n[!] Error fetching SSH command for session {session_id}!")
        print(e.stderr)
        return False
        
    # Replace placeholders
    ssh_cmd = ssh_cmd.replace("<privateKey>", private_key_path)
    ssh_cmd = ssh_cmd.replace("<localPort>", str(local_port))
    ssh_cmd = ssh_cmd.replace("ssh -i", "ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -i")
    
    print(f"[*] Opening local tunnel on port {local_port}...")
    
    # Run the SSH tunnel in the background
    process = subprocess.Popen(ssh_cmd, shell=True)
    pids.append(str(process.pid))
    return True

# Clear old PIDs
if os.path.exists("bastion_pids.txt"):
    os.remove("bastion_pids.txt")

success = True
success &= create_tunnel(master_ip, 22, 2222, "Master-SSH")
success &= create_tunnel(worker_ip, 22, 2223, "Worker-SSH")
success &= create_tunnel(master_ip, 6443, 6443, "Master-KubeAPI")

if success:
    with open("bastion_pids.txt", "w") as f:
        f.write("\n".join(pids) + "\n")
        
    print("\n[*] Tunnels are active in the background!")
    
    # Generate local inventory
    local_inv_path = "../ansible/inventory.local.ini"
    print(f"[*] Generating {local_inv_path}...")
    with open(local_inv_path, "w") as f:
        f.write("""[k3s_master]
127.0.0.1 ansible_port=2222 ansible_connection=ssh ansible_user=ubuntu ansible_ssh_private_key_file=ansible_key.pem

[k3s_worker]
127.0.0.1 ansible_port=2223 ansible_connection=ssh ansible_user=ubuntu ansible_ssh_private_key_file=ansible_key.pem

[k3s_cluster:children]
k3s_master
k3s_worker
""")
    
    print("\n==========================================")
    print("[*] Done! You can now run Ansible:")
    print("    cd ../ansible")
    print("    ansible-playbook main.yml")
    print("")
    print("[*] To close the tunnels later, run: kill $(cat bastion_pids.txt)")
    print("==========================================")
else:
    print("\n[!] Tunnel creation encountered errors. Cleaning up any opened tunnels...")
    for pid in pids:
        subprocess.run(["kill", pid], check=False)
