#!/bin/bash
# A simple loop to retry Terraform apply until OCI grants the ARM capacity
# Generated by Gemini 3.1 Pro

cd ../terraform/countriesApp

while true; do
  echo "Attempting to provision resources at $(date)..."
  
  # Run terraform apply and capture the exit code
  if terraform apply -var-file=./local/terraform.tfvars -auto-approve; then
    echo "====================================================="
    echo "SUCCESS! Oracle finally granted the ARM capacity!"
    echo "====================================================="
    break
  else
    echo "====================================================="
    echo "Still out of capacity. Sleeping for 5 minutes..."
    echo "====================================================="
    sleep 300
  fi
done
