apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: prod

commonLabels:
  env: prod

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: NODE_ENV
        value: production
  target:
    kind: Deployment
    name: backend
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: VITE_APP_VERSION
        value: prod-latest
  target:
    kind: Deployment
    name: frontend
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: quizgame.hiekkalaatikko.tech
    - op: replace
      path: /spec/rules/0/host
      value: quizgame.hiekkalaatikko.tech
  target:
    kind: Ingress
    name: quiz-ingress
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: hiekkalaatikko.tech
    - op: replace
      path: /spec/rules/0/host
      value: hiekkalaatikko.tech
  target:
    kind: Ingress
    name: frontpage-ingress
images:
- name: villejuhan1/quiz-backend
  newName: villejuhan1/quiz-backend
  newTag: happy-wolf-77d7f62
- name: villejuhan1/quiz-frontend
  newName: villejuhan1/quiz-frontend
  newTag: happy-wolf-77d7f62
- name: villejuhan1/frontpage
  newName: villejuhan1/frontpage
  newTag: happy-wolf-77d7f62
