apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Patches the postgres/backend/frontend deployment for production environment in prod workspace and configures ingress for it
resources:
- ../../base
- hpa.yaml

namespace: prod

labels:
- includeSelectors: true
  pairs:
    env: prod

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend
    spec:
      template:
        spec:
          containers:
            - name: backend
              env:
                - name: NODE_ENV
                  value: production
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
    spec:
      template:
        spec:
          containers:
            - name: frontend
              env:
                - name: VITE_APP_VERSION
                  value: prod-latest
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgres
    spec:
      template:
        spec:
          containers:
            - name: postgres
              resources:
                limits:
                  cpu: 1000m
                  memory: 1024Mi
                requests:
                  cpu: 250m
                  memory: 512Mi
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontpage
    spec:
      template:
        spec:
          containers:
            - name: frontpage
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: quizgame.hiekkalaatikko.tech
    - op: replace
      path: /spec/rules/0/host
      value: quizgame.hiekkalaatikko.tech
  target:
    kind: Ingress
    name: quiz-ingress
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: hiekkalaatikko.tech
    - op: replace
      path: /spec/rules/0/host
      value: hiekkalaatikko.tech
  target:
    kind: Ingress
    name: frontpage-ingress
images:
- name: villejuhan1/frontpage
  newName: villejuhan1/frontpage
  newTag: front-playful-robot-7af0c19
- name: villejuhan1/quiz-backend
  newName: villejuhan1/quiz-backend
  newTag: brave-whale-834a168
- name: villejuhan1/quiz-frontend
  newName: villejuhan1/quiz-frontend
  newTag: brave-whale-834a168
