apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/VilleJuhan1/Fullstack-websovelluskehitys-osa14-projekti.git'
    path: Infrastructure/kubernetes/apps/prod
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
