name: Backend tests

on:
  push:
    paths:
      - 'App/backend/**'
      - '.github/workflows/backend-test.yaml'
      - 'Infrastructure/docker/docker-compose-backend*.yml'
#  pull_request:
#    paths:
#      - 'App/backend/**'
#      - '.github/workflows/backend-test.yaml'

jobs:
  linter:
    # Only run this job if the commit messages contain '#backend-test'
    if: contains(toJSON(github.event.commits.*.message), '#backend-test')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: App/backend

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Using Node 20 as standard for modern apps

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  build-and-test:
    # Only run this job if the commit messages contain '#backend-test'
    if: contains(toJSON(github.event.commits.*.message), '#backend-test')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Infrastructure/docker

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Using Node 20 as standard for modern apps

      - name: Build Docker image
        run: docker compose -f docker-compose-backend-dev.yml build

      - name: Run app in Docker container
        run: docker compose -f docker-compose-backend-dev.yml up -d
        
      - name: Wait for service to start
        run: sleep 5

      - name: Run database migrations
        run: docker exec local_dev_db npm run db:migrate

      - name: Change directory to backend
        run: cd ../App/backend

      - name: Install test dependencies
        run: npm install

      - name: Test queries
        run: npm test