name: Landing Zone creation via Terraform (only plan)

on:
  push:
    paths:
      - 'Infrastructure/terraform/landingZone/**'
      - '.github/workflows/terraform-lz.yaml'

# For later: Add a functionality that applies the plan when it has been reviewed and is merged to main

jobs:
  terraform:
    # Only run this job if the commit messages contain '#lz'
    if: contains(toJSON(github.event.commits.*.message), '#lz') 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Infrastructure/terraform/landingZone
    env:
      # Terraform automatically maps these to your variables
      TF_VAR_tenancy_ocid:      ${{ secrets.OCI_TENANCY_OCID }}
      TF_VAR_user_ocid:         ${{ secrets.OCI_USER_OCID }}
      TF_VAR_fingerprint:       ${{ secrets.OCI_FINGERPRINT }}
      TF_VAR_private_key:       ${{ secrets.OCI_PRIVATE_KEY }}
      TF_VAR_region:            ${{ secrets.OCI_REGION }}
      TF_VAR_projects:          ${{ secrets.OCI_PROJECTS }}
    steps:
      - uses: actions/checkout@v4
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="address=${{ secrets.OCI_STATE_PAR_URL }}" \
            -backend-config="update_method=PUT"

      - name: Terraform Plan
        run: terraform plan